import random


_messages = [
    "I know that everyone talks about this on dating apps, but if loving 'The Office' is wrong, then I don’t want to be Dwight.",
    "So, come here often?",
    "You know, I've been waiting for you to message me, but I guess I'll take one for the team.",
    "Do you believe in love at first swipe, or should we unmatch and then match again?",
    "Obviously, we'd meet on an app — because you're a total snack.",
    "Does swiping through this dating app count as 'exercise'?",
    "Do you need me to call the fire department? I bet your phone is full of matches.",
    "Who's the person in your first photo? My grandmother was asking.",
    "That dog looks so cute, can you give them my number?",
    "We can say we met on Spotify because you're the hottest new single.",
    "Glad we matched when we did, my thumb was getting tired!",
    "Two wrongs don't make right, but two rights make a perfect match.",
    "Some people think with their hearts, some with their heads, but I'm glad we both think with our thumbs.",
    "Hmm, I think your first message to me must have gotten lost in cyberspace... It's OK. I'll send you one.",
    "If you had to describe my profile in three words, what would you choose? And why would they be iconic, perfect, and flawless?",
    "Why do bartenders use blenders? To break the ice.",
    "Going to Trader Joe’s, do you need anything?",
    "Are you more afraid of spiders or saying, “You too!” when a server says, “Enjoy!”?",
    "So, do you have any good pickup lines?",
    "People always say they want to be the person their pet thinks they are, but my pet knows that all I do is watch bad TV in my pajamas and eat cereal for every meal.",
    "My mom just asked me what “WAP” meant… any advice on how to navigate that conversation?",
    "Using only emojis, can you explain to me your first time paying taxes?",
    "What’s your least favorite pasta shape?",
    "If your mom were a shoe, what kind of shoe would she be?",
    "If Napoleon Dynamite and Joe Exotic started a band, what would it be called? Liger King.",
    "What kind of kitchen appliance are you? Don't say blender. Everybody says blender.",
    "Should I start this conversation with a bad pickup line or by just saying hello?",
    "Do you also still think about all the embarrassing things you said in middle school, or are you a well-adjusted adult?",
    "Big. Gigantic. Enormous. Huge... I never liked small talk.",
    "If you wrote a memoir, what would the title be? Mine would be 'Overthinking Opening Messages.'",
    "Where did the f*ckboy go to college? U Up.",
    "I don't want to flood your inbox, but dam — you look good.",
    "I don't like dried fruits, but I’d meet you for a date.",
    "I’d love to grab margs sometime and taco ‘bout our feelings.",
    "Are you a library book? Because I’d like to check you out.",
    "Are you a barista? Because I like you a latte.",
    "So hoppy you matched me back, I couldn't wheat to talk to you.",
    "Hopefully, this app will lead to a great meal.",
    "What do you call a row of trucks? A pickup line.",
    "Are you familiar with the work of Claude Monet? Because you make quite the impression.",
    "I'm trying to think of a Postmates pickup line, but I need some help with the delivery.",
    "They must call you Earl Grey because you're such a hot tea.",
    "I know it's cheesy, but matching with you is too Gouda to be true.",
    "Trying to think of a fruit or vegetable joke, but I can't produce much under pressure.",
    "Water you doing later? Want to get drinks?",
    "Straight Forward",
    "I think you're super cute and funny. That's it. That's the tweet.",
    "Broad City! (I've been thinking of something funny to say for an hour.)",
    "Hooking up is cool, but have you ever matched with someone on a dating app and had them send a really good first message?",
    "I always remember my reusable bags at the supermarket, which has to merit a response.",
    "What's a nice person like you doing in a place like this?",
    "Let's cut to the chase, do you share food on a first date?",
    "You didn't 'Super Like' me, but it's OK, I'll take your number as an apology.",
    "I'm not great at starting conversations, do you want to try?",
    "How about I start this conversation, and you can start the next one?",
    "Is our anniversary when we first matched or when we first messaged?",
    "Aww, you're so considerate to let me start this conversation.",
    "What's down? (It's the cooler cousin of 'What's up?')",
    "How are we doing tonight? Have you dined with us before? Let me know if you have any questions about the menu.",
    "Gosh! Stop messaging me! You're blowing up my inbox!",
    "Do you normally go for people that are super good looking or super funny? Don't worry. I'm both.",
    "The Ball Rolling",
    "Not to be salty, but I bet a pitcher I know a better margarita place than you.",
    "Wanna sit next to me in silence as we both pretend to work but really look at memes?",
    "Quick! Settle a bet, are you someone that’s going to match with me on this app but never actually message me?",
    "Want to try to explain the rules of football to me? I’ll buy drinks.",
    "If I give you my number, will you text me to remind me to drink water during the day?",
    "I don’t need your astrology sign, but I do want to know what your late-night GrubHub order is.",
    "Be honest, did your ex take any of the photos in your profile?",
    "What’s the worst opening line you’ve even got on a dating app? (It can’t be this one.)",
    "I’d ask where should I tell my mom we met, but I don’t think dating apps deserve the stigma, and I think it’s imperative to be honest about them, even to boomers.",
    "Basmati or long-grain? (Yes, I got that from Love Island.)",
    "What should I make for dinner? Keep in mind I have no groceries and I can’t cook.",
    "How do you feel about cuffed pants? May or may not inform my outfit on our first date.",
    "Who’s your celebrity crush, and why is it Rhianna?",
    "Just want to point out, if you want to message me first, you still can.",
    "Would you rather always be a little bit damp or a little bit sticky?",
]


def get_random_message():
    return random.choice(_messages)
